name: update-updates-json-file
on:
  workflow_dispatch:
    inputs:
      githubRef:
        description: "The tag to associate with the release"
        required: true
        default: ${{ github.ref_name }}
      xpiFilePath:
        description: "Path to the XPI file"
        required: true
        default: "Downloads/rikaitan-firefox-selfhosted.xpi"
      metadataBranch:
        description: "Branch to get updates.json from"
        required: true
        default: "metadata_selfhosted"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      # intentially do not use cache to keep the build more comprehensible and sandboxed
      - name: Install dependencies
        run: npm ci

      - name: Get updates.json from metadata branch
        run: |
          # Get the updates.json file from the specified metadata branch
          mkdir -p Downloads
          git show ${{ inputs.metadataBranch }}:updates.json > Downloads/updates.json

      - name: Run update_updates_json_file.ts script
        run: |
          npm run-script update_updates_json_file
        env:
          githubRef: ${{ inputs.githubRef }}
          xpiFilePath: ${{ inputs.xpiFilePath }}
          updatesFilePath: Downloads/updates.json

      # update updates.json so that all people who have
      # the selfhosted version installed get the new update
      # https://extensionworkshop.com/documentation/manage/updating-your-extension/
      - name: Checkout metadata branch for commit
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.metadataBranch }}

      - name: Copy updated updates.json to metadata branch
        run: |
          mv -f -- Downloads/updates.json updates.json

      - name: Commit updated updates.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add updates.json
          git commit -m "Update updates.json for release ${{ inputs.githubRef }}"

      - name: Push changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # pin@master
        with:
          branch: ${{ inputs.metadataBranch }}
